# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
